### ISSUE TITLE
Github > README.me

### ISSUE THREAD

**Issue by johannpinson** [CarinaChenot/hetic-p2020-01#18]
Make some changes to improve the README.md :

- [x] Use section to discern the different parts, with at least this minimal 3 parts "how to" : Installation, Running and Building the app
- [x] Add precision about (S)CSS naming convention (BEM ? OCCSS ? etc.)
- [x] So don't forget to specify any requirement (node.js >= 6.4 ? npm -g yarn ? etc.)
- [x] You can add anything else useful (credit, git commit msg convention, badge, logo, screenshot, etc.)

**Comment by CarinaChenot** [comment]
Merged on #23

**Comment by johannpinson** [comment]
The URL must also be inside the README and not only inside the github description.

You can add a badge for this :
https://www.netlify.com/press/
https://shields.io/

**Comment by johannpinson** [comment]
Notify @CarinaChenot (because I can't reopen the issue)
